export class CustomerInfo{
    name: string;
    effectiveDate:string;
    address: string;
    phone:string;
    homebuiltin:number;
    area:string;
    email:string;
    dateofbirth:string;
    pastpropertyclaimsorlosses:string;
    maritalstatus:string;
    runningbusinessfromhome:number;
    smokerstatus :string;
    criminalconvictions:string;
    street:string;
    unit:string;
    city:string;
    zip:string;
    state:string;
    coveragestartdate:string;
    currentlyproissues:string;
    firstname: string;
    lastname: string;
    gender:string;
    ocuupation:string;
    age:string;
    businessfromhome:string;
    petsathome:string;
    nameofinsurer:string;
    cancelationyear:string;
    cancelpolicy:string;
    cancelationreason:string;
}